### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by Ar-ALN** [Yanan-Wang-cs/ClonedPerson#1]
Hello, first of all thanks for your anwesome work !
Could you please provide the environment with the libs you used for the demo, because I'm struggling to install them all.

Thank you guys !

**Comment by Yanan-Wang-cs** [comment]
Hi, thanks for your attention. 

I'm sorry I don't get your point. The environment of which step are you struggling? We have 1. Pedestrian detection, 2. Person view qualification by pose detection, 3. Clothes and keypoint detection, 4. Similarity-Diversity Expansion, 5. Generate 3D characters, 6. Export 3D characters, 7. Unity3D Simulation and Rendering, 8. Crop dataset

We will provide more details later in our [README.md](https://github.com/Yanan-Wang-cs/ClonedPerson/tree/main/pipeline#readme).

**Comment by ShengcaiLiao** [comment]
The installation instructions are now detailed in https://github.com/Yanan-Wang-cs/ClonedPerson/tree/main/pipeline
