### ISSUE TITLE
Training parameters

### ISSUE THREAD

**Issue by XaryWorld** [Yanan-Wang-cs/ClonedPerson#10]
Can you share the training parameters of the experimental QAConv
![图片1](https://github.com/Yanan-Wang-cs/ClonedPerson/assets/108608122/8dd83afc-9a21-4183-ad98-36f0a459a5b0)

**Comment by Yanan-Wang-cs** [comment]
Hi, thank you for your interest.
As our paper mentioned, we keep the same settings for each method.
For QAConv, we use QAConv 2.0, and below are the parameters:

main.py --testset cuhk03_np_detected,market,msmt --data-dir Data/ --exp-dir ../clonedperson/ --method QAConv50_IBNb_GS --sub_method res50-layer3-f64_pre0_clip512_lr3_bs64-k4_epsgpu_run1 --dataset clonedperson

**Comment by XaryWorld** [comment]
Thank you for your reply
