### ISSUE TITLE
Will you release in Baidu disk？Thanks！

### ISSUE THREAD

**Issue by zzk2021** [Yanan-Wang-cs/ClonedPerson#2]

**Comment by Yanan-Wang-cs** [comment]
Thank you for your attention.
I could not connect to the Baidu disk recently, therefore I uploaded the dataset to quark. Please visit this [link](https://pan.quark.cn/s/4b764db4462f) to download.

**Comment by zzk2021** [comment]
I have downloaded from Google Drive source, but the link which you newly upload have an empty folder.

**Comment by ShengcaiLiao** [comment]
Thanks for reporting this. It was there at first, but we don't know when and why it was deleted by the platform. We'll try other solutions.
