### ISSUE TITLE
你好，这个工作是否可以通过语言或者选择器控制生成的图像内容？

### ISSUE THREAD

**Issue by zzk2021** [Yanan-Wang-cs/ClonedPerson#3]

**Comment by ShengcaiLiao** [comment]
你好，能再细说下你想控制哪些方面的生成吗？

**Comment by zzk2021** [comment]
比如行人衣装，体型，装饰，性别。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Shengcai ***@***.***>
发送时间: 2023年1月11日 13:29
收件人: ***@***.***>
抄送: ***@***.******@***.***>; ***@***.***>
主题: Re: [Yanan-Wang-cs/ClonedPerson] 你好，这个工作是否可以通过语言或者选择器控制生成的图像内容？ (Issue #3)


你好，能再细说下你想控制哪些方面的生成吗？

―

**Comment by ShengcaiLiao** [comment]
这些是可以控制的，体型，装饰，性别是通过模型参数选择，衣装是我们ClonedPerson方法贴上去的，来源图片可以选择。

**Comment by zzk2021** [comment]
好的，谢谢。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Shengcai ***@***.***>
发送时间: 2023年1月11日 13:49
收件人: ***@***.***>
抄送: ***@***.******@***.***>; ***@***.***>
主题: Re: [Yanan-Wang-cs/ClonedPerson] 你好，这个工作是否可以通过语言或者选择器控制生成的图像内容？ (Issue #3)


这些是可以控制的，体型，装饰，性别是通过模型参数选择，衣装是我们ClonedPerson方法贴上去的，来源图片可以选择。

―
