### ISSUE TITLE
Sorry to boring you,I want to konw how you compile mmdet in 1Pedestron?

### ISSUE THREAD

**Issue by zzk2021** [Yanan-Wang-cs/ClonedPerson#4]
I can't use operator like dcn cause my cuda version is 10.2，but you compile it with cuda10.1

**Comment by zzk2021** [comment]
我没找到编译入口，比如setup.py

**Comment by zzk2021** [comment]
ok，我自己写了个setup.py，成功编译了提供的算子。

**Comment by hex-xi** [comment]
> ok，我自己写了个setup.py，成功编译了提供的算子。

您好，我也遇到了这个问题，请问这个setup.py怎么写啊？不知道您方便提供您的示例代码吗？

**Comment by ShengcaiLiao** [comment]
Hi, thank you for the interest. For the first step, pedestrian detection, please refer to the project [Pedestron](https://github.com/hasanirtiza/Pedestron). We follow the [installation instructions](https://github.com/hasanirtiza/Pedestron#installation) there, specifically https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md. You can also find a setup.py in that project. If you have further trouble, please check issues in that project, or post your own issues there. Dr. Irtiza Hasan will be happy to answer you.

**Comment by hex-xi** [comment]
> Hi, thank you for the interest. For the first step, pedestrian detection, please refer to the project [Pedestron](https://github.com/hasanirtiza/Pedestron). We follow the [installation instructions](https://github.com/hasanirtiza/Pedestron#installation) there, specifically https://github.com/hasanirtiza/Pedestron/blob/master/INSTALL.md. You can also find a setup.py in that project. If you have further trouble, please check issues in that project, or post your own issues there. Dr. Irtiza Hasan will be happy to answer you.

Thanks, I will have a try!
