### ISSUE TITLE
5Characters：Loading checkpoint (getLabels wrong)

### ISSUE THREAD

**Issue by hex-xi** [Yanan-Wang-cs/ClonedPerson#8]
Hello, thank you for your excellent work~
I have some other problems when I try the step5 in the pipeline:

1. I am not clear about how to run step5 successfully. 
①It warns that I don't have cuda11.0, because I used cuda10.0 that time. Is the cuda11.0 necessary? Or there exist another problem in fact？
②How to fix this checkpoint problem？

2. If I want to add new cloth model, what should I do? Just adding a new floder (conclude .mhclo, .mhmat, .obj, .thumb flie ) (floder name index++) in */ClonedPerson/pipeline/5characters/models would be OK?

Here are the error details:
```
(clonedperson_4cluster) hex@TP:~/work/ClonedPerson/pipeline/5characters$ sh demo.sh
2023-04-14 16:48:17.545442: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64
2023-04-14 16:48:17.545463: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
save_step_open: False

Create IBN-Net model resnet50_ibn_b.

Using cache found in /home/hex/.cache/torch/hub/XingangPan_IBN-Net_master
/home/hex/miniconda3/envs/clonedperson_4cluster/lib/python3.7/site-packages/torchvision/transforms/transforms.py:281: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Loading checkpoint...
=> Loaded checkpoint 'checkpoint.pth.tar'
0 img/pair_0.989210_56_0_137_249_1_21_1.jpeg 8
Error: getLabels wrong, 0 [1, 2, 3, 4] ['4.50873600874602E+053']
Error: getLabels wrong, 1 [1, 2, 3, 4] ['4.50873600874602E+053']
Error: getLabels wrong, 2 [1, 2, 3, 4] ['4.50873600874602E+053']
Error: getLabels wrong, 3 [1, 2, 3, 4] ['4.50873600874602E+053']
Traceback (most recent call last):
  File "clonedperson.py", line 640, in <module>
    main(parser.parse_args())
  File "clonedperson.py", line 549, in main
    homography_result, cloth_img, model_landmark, save_name, model_img = PerspectiveHomography([source_folder + cloth_path, cloth_landmark], model_list[model_index%len(model_list)], [source_folder + cloth_path2, cloth_landmark2], cloth_index)
  File "clonedperson.py", line 152, in PerspectiveHomography
    H, mask = cv2.findHomography(cloth_keypoints_position, model_keypoints_position)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/calib3d/src/fundam.cpp:378: error: (-5:Bad argument) The input arrays should be 2D or 3D point sets in function 'findHomography'
```

**Comment by Yanan-Wang-cs** [comment]
Hi, thank you for your attention.

> It warns that I don't have cuda11.0, because I used cuda10.0 that time. Is the cuda11.0 necessary? Or there exist another problem in fact？

For this warning message, I think it's ok, and according to the error message, you already start the generating process.

> How to fix this checkpoint problem？

According to the error message, we could locate to the "getLables" function in clonedperson.py. And this is because of the wrong type of "getLabels_list" parameter, which should be ['450', '873', '600', ..., '996'] instead of ['4.50873600874602E+053']. So I think there might have some problem in "Resources/model.csv" or the parameter "model_landmark" in clonedperson.py.

> If I want to add new cloth model, what should I do? Just adding a new floder (conclude .mhclo, .mhmat, .obj, .thumb flie ) (floder name index++) in */ClonedPerson/pipeline/5characters/models would be OK?

If you want to add a new cloth model, you should add all the cloth files(e.g. .mhclo, .mhmat, .obj) downloaded from MakeHuman community under "models/your_foldername", and then labeled the keypoints positions in "Resources/model.csv". The data format is: "your_foldername, cloth type, keypoints in UV map, mapping orders according to the cloth keypoint detection model's output(front-view), mapping orders according to the cloth keypoint detection model's output(back-view), front-view bounding-box position in UV map, HomoGeneousExpansion area"

**Comment by hex-xi** [comment]
Thank you very much for your detailed and patient answer! I'll try it.

**Comment by hex-xi** [comment]
> 

Thank you very much for your detailed and patient answer! I'll try it.

**Comment by hex-xi** [comment]
> Hi, thank you for your attention.
> 
> > It warns that I don't have cuda11.0, because I used cuda10.0 that time. Is the cuda11.0 necessary? Or there exist another problem in fact？
> 
> For this warning message, I think it's ok, and according to the error message, you already start the generating process.
> 
> > How to fix this checkpoint problem？
> 
> According to the error message, we could locate to the "getLables" function in clonedperson.py. And this is because of the wrong type of "getLabels_list" parameter, which should be ['450', '873', '600', ..., '996'] instead of ['4.50873600874602E+053']. So I think there might have some problem in "Resources/model.csv" or the parameter "model_landmark" in clonedperson.py.
> 
> > If I want to add new cloth model, what should I do? Just adding a new floder (conclude .mhclo, .mhmat, .obj, .thumb flie ) (floder name index++) in */ClonedPerson/pipeline/5characters/models would be OK?
> 
> If you want to add a new cloth model, you should add all the cloth files(e.g. .mhclo, .mhmat, .obj) downloaded from MakeHuman community under "models/your_foldername", and then labeled the keypoints positions in "Resources/model.csv". The data format is: "your_foldername, cloth type, keypoints in UV map, mapping orders according to the cloth keypoint detection model's output(front-view), mapping orders according to the cloth keypoint detection model's output(back-view), front-view bounding-box position in UV map, HomoGeneousExpansion area"

Thank you very much for your detailed and patient answer! I'll try it.
