### ISSUE TITLE
some questions about clothes keypoints pi

### ISSUE THREAD

**Issue by XaryWorld** [Yanan-Wang-cs/ClonedPerson#9]
May I ask if the eight clothing styles mentioned in the article and the key points on the provided UV images are manually labeled?
![ZN3F5R@}SZ1FXPZ318L){FO](https://github.com/Yanan-Wang-cs/ClonedPerson/assets/108608122/553e05ff-2c14-48b5-911f-0d990bdea22d)

**Comment by Yanan-Wang-cs** [comment]
For the image you mentioned above is manually labeled to indicate the exact keypoint positions in each clothing style. For our generation process, we use DeepFashion and DeepFashion2 to train a cloth keypoint detection model and use the outputs instead of manually labeled.
